# Generated by Django 3.2.7 on 2021-10-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categrory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('disc', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klog.categrory')),
            ],
        ),
    ]
